version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dmhouse
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123admin#"
      POSTGRES_DB: dmhouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-dmhouse
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: